version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: wa_docs_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-wa_docs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wa_docs}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data