version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: wa_docs_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
networks:
  default:
    name: wa_docs_network
    external: true