@url = http://localhost:8080/api/v1/folder

@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YV9kb2NzIiwiaWF0IjoxNzQ1MjYzNDI3LCJleHAiOjE5NjEyNjM0MjcsInN1YiI6ImJlbmVkaWN0b3RhdmlvQHR1YW1hZWFxdWVsYXVyc2EuY29tIn0.4r7hLANIXJDChoebFgBNyY-70KtP6Ul1DVJjeOR4724

### @name GetFolder
GET {{url}}/13 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### @name CreateFolder
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "name": "Folder Root 1",
    "projectId": 1, //
    "level": 1, // Level in folder tree
    "parentId": 11 // Folder parent
}

### @name UpdateFolder
PATCH {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "name": "Folder 2"
}

### @name GetTree
GET {{url}}/tree?projectId=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### @name DeleteFolder
DELETE {{url}}/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}