@url = http://localhost:8080/api/v1/mockserver
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YV9kb2NzIiwiaWF0IjoxNzQwNDM5NzkzLCJleHAiOjE5NTY0Mzk3OTMsInN1YiI6ImJlbmVkaWN0b3RhdmlvQHR1YW1hZWFxdWVsYXVyc2EuY29tIn0.j2HKqp5Es9ivO-ziA7xs5lKU1EmfLq3H5yBy1iZxIHg

# @name CreateMockServer
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mock Server 1",
  "path": "/api/mock",
  "method": "GET",
  "headers": "{\"Content-Type\": \"application/json\"}",
  "projectId": 1,
  "statusCode": 200,
  "bodyResponse": "{\"message\": \"Request was successful\"}"
}