@url = http://localhost:8080/api/v1/team

@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YV9kb2NzIiwiaWF0IjoxNzQwNDM5NTQ2LCJleHAiOjE5NTY0Mzk1NDYsInN1YiI6ImJlbmVkaWN0b3RhdmlvQHR1YW1hZWFxdWVsYXVyc2EuY29tIn0.DQATb-NQgEb5KxEk8edoLLwgJFjN4wZ74k3JcD_YO-4

# @name CreateTeam
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "name": "test_team_55555",
    "description": "test_team_description_2 edmkde eomdedmedmemdoimeod eoidoiekmdmeoimmoidmoiemdo ediediedioied",
    "ownerId": 1
}

# @name GetTeam
###
GET {{url}}/1 HTTP/1.1


# @name UpdateTeam
###
PATCH {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "name": "test_team_updated"
}

# @name DeleteTeam
###
DELETE {{url}}/1 HTTP/1.1


# @name DeleteManyTeams
###
DELETE {{url}}/bulk HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

[
    3
]

# @name GetTeamByUserId
###
GET {{url}}?user=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}