@url = http://localhost:8080/api/v1/user
@bearerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YV9kb2NzIiwiaWF0IjoxNzM5NzE2MDc5LCJleHAiOjE3Mzk3MzA0NzksInN1YiI6ImJlbmVkaWN0b3RhdmlvQHR1YW1hZWFxdWVsYXVyc2EuY29tIn0.6_x7OeD3vGGxjISV8XHBiY_PmnW-NQBA9P5OK_lCDHM

# @name getUser
GET {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### @name getUsersByEmail
GET {{url}}?email=benedictotavio@tuamaeaquelaursa.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}