name: Maven Workflow
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches: [ main ]

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "oracle"
          cache: maven
      - name: Build with Maven
        run: mvn clean install -B -DskipTests

  java-tests:
    needs: [java-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "oracle"
          cache: maven
      - name: Run tests with Maven
        run: mvn test
  
  java-coverage:
    needs: [java-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "oracle"
          cache: maven
      - name: Get Jacoco coverage
        run: mvn jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: jacoco.xml